vim.cmd [[packadd packer.nvim]]
require("plugins")
require("settings")
require("key-maps")
require("nvim-tree-config")
require("cmp-config")
require("telescope-config")
require("treesitter-config")
require("lsp-config")
require("lsp-installer")
require("codegpt-config")
